apiVersion: v1
kind: Pod
metadata:
  name: pod-missing-secret
  namespace: lab-04-config
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: ["sh", "-c", "env && sleep 3600"]
    env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: nonexistent-secret   # this secret does not exist
          key: DB_PASS
