apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broken-pvc
  namespace: lab-16-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: does-not-exist   # no StorageClass with this name exists in the cluster
