apiVersion: v1
kind: Pod
metadata:
  name: rbac-tester
  namespace: lab-18-rbac
spec:
  serviceAccountName: lab-reader
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]
