apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-bad-probes
  namespace: lab-05-probes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-bad-probes
  template:
    metadata:
      labels:
        app: nginx-bad-probes
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz    # nginx does not serve this path — returns 404
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 9090        # nginx does not listen on this port — connection refused
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
