apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: lab-17-statefulsets
spec:
  clusterIP: None   # headless — no virtual IP, DNS returns individual pod IPs
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
