apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capstone-dev
namePrefix: dev-
resources:
- ../../base
images:
- name: nginx
  newTag: "1.25"
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: backend
commonLabels:
  env: dev
