apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: lab-13-workloads
spec:
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      containers:
      - name: collector
        image: busybox:1.36
        command: ["sh", "-c", "echo 'log-collector running on node' $(hostname) && sleep 3600"]
