apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: capstone
data:
  APP_ENV: "production"
  APP_NAME: "capstone-platform"
  BACKEND_URL: "http://backend-svc"
  LOG_LEVEL: "INFO"
