apiVersion: v1
kind: Pod
metadata:
  name: pod-burstable
  namespace: lab-11-resources
spec:
  containers:
  - name: nginx
    image: nginx:stable
    resources:
      requests:
        cpu: "50m"
        memory: "32Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
