apiVersion: v1
kind: Pod
metadata:
  name: pod-guaranteed
  namespace: lab-11-resources
spec:
  containers:
  - name: nginx
    image: nginx:stable
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "64Mi"
