apiVersion: v1
kind: Pod
metadata:
  name: nginx-bad-image
  namespace: lab-01-pods
  labels:
    app: nginx-broken
spec:
  containers:
  - name: nginx
    image: nginx:stable 
    ports:
    - containerPort: 80
