apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test
  namespace: lab-29-nodes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-test
  template:
    metadata:
      labels:
        app: node-test
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
