apiVersion: v1
kind: Pod
metadata:
  name: app-d
  namespace: speed-32
spec:
  containers:
  - name: app-d
    image: nginx:stable
    resources:
      requests:
        cpu: "100"
        memory: "500Gi"
