apiVersion: v1
kind: Pod
metadata:
  name: missing-caps-pod
  namespace: lab-19-security
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: app
    image: nginx:stable
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      # Missing: capabilities.drop: ["ALL"]
      # restricted policy requires all capabilities to be dropped
